exports.DAY_KEYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

exports.WORK_TODAY = 'TODAY';
exports.WORK_EVERYDAY = 'EVERYDAY';
exports.WORK_24x7 = '24x7';
exports.WORK_NOT_WORKING = 'NOT_WORKING';

exports.BREAK_LUNCH = 'LUNCH';
exports.BREAK_REST = 'REST';

exports.EVENT_OPEN = 'OPEN';
exports.EVENT_CLOSE = 'CLOSE';

exports.STATUS_OPENED = 'OPENED';
exports.STATUS_WILL_CLOSE_IN_TIME_FOR_BREAK = 'WILL_CLOSE_IN_TIME_FOR_BREAK';
exports.STATUS_WILL_CLOSE_IN_TIME = 'WILL_CLOSE_IN_TIME';

exports.STATUS_WILL_OPEN_AT_TIME = 'WILL_OPEN_AT_TIME';
exports.STATUS_WILL_OPEN_AT_DAY_AT_TIME = 'WILL_OPEN_AT_DAY_AT_TIME';
exports.STATUS_WILL_OPEN_TOMORROW_AT_TIME = 'WILL_OPEN_TOMORROW_AT_TIME';
exports.STATUS_WILL_OPEN_DAY_AFTER_TOMORROW_AT_TIME = 'WILL_OPEN_DAY_AFTER_TOMORROW_AT_TIME';

exports.STATUS_WILL_OPEN_IN_TIME = 'WILL_OPEN_IN_TIME';

exports.STATUS_WILL_OPEN_IN_TIME_FROM_BREAK = 'WILL_OPEN_IN_TIME_FROM_BREAK';
exports.STATUS_WILL_OPEN_AT_TIME_FROM_BREAK = 'WILL_OPEN_AT_TIME_FROM_BREAK';
